name: heart_steel
description: "亚索，起来叠钢了"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  url_launcher: ^6.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/SFX/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"